### ISSUE TITLE
Connector is not fetching data

### ISSUE THREAD

**Issue by diegosueiro** [hellowearemito/dataconnector-facebook#2]
After configuring the connector and creating the data source when I try to use it in a report (by creating a table) I receive the following error message:

**The server encountered an internal error and was unable to complete your request.
Error ID: 68fc0656**

**Comment by djozsef** [comment]
Hello @diegosueiro,

Thanks for reporting this issue. We are aware of a problem that in some cases the Facebook Marketing API throws unknown errors if too much of data is about to transferred to the data connector. We are working on a solution. 
As a workaround you can try to narrowing down the data set to fetch by selecting a specific campaign, ad set or ad on the settings page.

I hope it helps your case.

**Comment by diegosueiro** [comment]
@djozsef,

Thanks for the explanation.

I don't know how to perform this configuration.
Find below the configuration that I'm using.
Do you have a template that I can use?

![screenshot 2017-09-27 at 06 10 36](https://user-images.githubusercontent.com/598588/30896815-cec16614-a34a-11e7-9265-1565bb742f67.png)

**Comment by diegosueiro** [comment]
I created some Report Level filters using the Campaign Name, Ad Set Name, Ad Name and added Date Range for yesterday but the issue remains.

**Comment by djozsef** [comment]
Hello @diegosueiro,

The Ad Account and Campaign filter setting is on the data connector's settings page. So when you add the "Native Facebook Connector" when creating a new datasource you get this screen after completing the authorization steps: 
![image](https://user-images.githubusercontent.com/1174548/30897884-f8f62952-a358-11e7-874c-c51c4dbddf15.png)

You can select you the Ad Account or camapaign here.

**Comment by diegosueiro** [comment]
@djozsef ,

Only my Facebook Ad Account is appearing. There is no option to select a campaign.
And every time I click on the connector I have to choose my Facebook Ad Account.
I tried to add a new data source but I can't still see the option to add a Campaign.

**Comment by halsandr** [comment]
+1 @diegosueiro , I am also getting the same error and the dropdown only shows me the Ad Accounts (No Campaigns).

As you can see in the screenshot it shows the business manager name instead of the account names but this isn't a huge problem as I can work out which is which from the IDs.
<img width="372" alt="screen shot 2017-10-04 at 15 27 49" src="https://user-images.githubusercontent.com/13107438/31181359-01298d92-a919-11e7-8eae-1b3b89311514.png">

**Comment by Kjetil-Digital-Ice** [comment]
Same issue as above. Getting system error on charts. Wont show campaign names for filtering to reduce size of request, The listed Accounts is also fewer than expected. Please advice!

**Comment by djozsef** [comment]
Hello @diegosueiro,

The data connector works based on the Business Manger assigned campaign permissions. Could you please check if you are assigned to a Business Manager and you have sufficient privileges to read insights data?

**Comment by djozsef** [comment]
Hello @diegosueiro @Kjetil-Digital-Ice ,

Regarding the issue with data fetching we are working on a solution. Please give us a little time to release a new version that handles incomplete Facebook responses.

**Comment by diegosueiro** [comment]
@djozsef,

I'm the Ad account admin.

![screenshot 2017-10-11 at 05 48 20](https://user-images.githubusercontent.com/598588/31422772-d6f2663c-ae47-11e7-89e3-382a538c88a3.png)

**Comment by gonczo** [comment]
Thank you for your work.
I would like to share my experiences about the data connector.

Authorisation - It's working fine.
Facebook Ad accounts - Can't see all of them, despite my admin status.
Variables, metrics - It's not able the fetch all of the Facebook Ads data through the connector (see the screenshot below). 

![image](https://user-images.githubusercontent.com/31764613/31487571-53f45d68-af3b-11e7-90be-ed3103587e96.png)

**Comment by djozsef** [comment]
Hello @diegosueiro @Kjetil-Digital-Ice,

We have released an update that addresses the "System error" type of issues that occurred due to a Facebook Graph API problem. Please re-add the connector to make sure you use the latest version.

The problem is that Facebook Graph API might throw 500 errors if too much of data is requested or the query runs too long. We addressed this issue by adding a date range control (and respective options) to the connector parameters. The default timeframe is 28 days but you can define any range. Please note that  defining a too wide date range can result in the very same error we experienced above.

**Comment by diegosueiro** [comment]
@djozsef,

I deleted and created a new data source with the Native Facebook Connector and issue remains the same.

**Comment by djozsef** [comment]
Hello @diegosueiro,

Do you use our Community Facebook App or your own? Because if you use your own FB app, you need to add your Ad Account to the enabled accounts in the app's settings.

There is no need to do this with out Community App, because we have a higher privilege level that lifts this limitation.

**Comment by djozsef** [comment]
Hello @halsandr,

Regarding your problem with incomplete Ad Account list: are you using our Community App or your own FB app?

**Comment by halsandr** [comment]
@djozsef I was using your community app through the DataStudio "Explore Connectors" page, I have tried creating a new data source but both the problems still remain (As per the screenshot I posted previously). I have now received a more verbose error on adding a chart if this helps (I will post screenshot below).

<img width="600" alt="screen shot 2017-11-06 at 10 15 15" src="https://user-images.githubusercontent.com/13107438/32436412-e9bebed4-c2db-11e7-91ca-c69d974d86a0.png">

**Comment by djozsef** [comment]
Hello @halsandr ,

Thank you for the verbose error message it helped us track down a the issue. It is related to Facebook throttling problem, we are working on it.
Will get back to you as soon as we get it fixed.

**Comment by halsandr** [comment]
@djozsef I have come across a similar problem previously that was caused by the Facebook API App being in Developer mode, so it only let you use it with pages/Ad accounts that the app creator had access to.

Have you Submitted your Facebook app for review to be made public?

**Comment by djozsef** [comment]
Hello @halsandr,

We have managed to settle the FB Graph API throttling problem so the issue you reported should be resolved by now. Could you please check if the problem is solved for your accounts too?

Many thanks!

**Comment by halsandr** [comment]
@djozsef thank you, that's much better,

I can now see the Campaigns in the dropdown after adding the Connector (although the Business Manager name is still being displayed instead of the Ad Account name for each one), I can also now get data to display in the tables in DataStudio.

**Comment by diegosueiro** [comment]
@djozsef,

I can confirm that now it is working.

One questions: the Outbound clicks CTR metric should be configured as Percent type?

**Comment by diegosueiro** [comment]
@djozsef,

It seems that Date Range control is not working properly. Changing the range always produce the same results.

**Comment by djozsef** [comment]
Hello @diegosueiro 

The date range filter has a known problem (see #8 ), we are working on it.
Regarding your CTR question: the connector does not curate data at the moment so all FB Ad Insigts API characteristics apply. I guess the values are to be interpreted as percents.
