### ISSUE TITLE
No Date Dimensions

### ISSUE THREAD

**Issue by drochUNO** [hellowearemito/dataconnector-facebook#8]
Hi there!

I cannot select any DATE dimension in the Facebook connector data in order to create a evolution chart of the  - in example - Reach of the account.
![screenshot-datastudio google com 2018-01-03 10-12-35-353](https://user-images.githubusercontent.com/35061312/34514738-1e4a2e16-f06f-11e7-8397-65a9c567068f.png)

![screenshot-datastudio google com 2018-01-03 10-14-10-159](https://user-images.githubusercontent.com/35061312/34514737-1e2cf738-f06f-11e7-8717-2db5aa7fca60.png)

I just can select the above listed Metrics and Dimensions, and I would appreciate any help to create or select DATE dimensions.

Best regards;

David

**Comment by tomvweekes** [comment]
Bump this. I totally agree. Since there's no date dimension, it doesn't even follow the data filter for score cards or tables. This is essentially useless unless you run all temporary campaigns

**Comment by djozsef** [comment]
Hello @tomvweekes @drochUNO,

thanks for the report. We have manged to reproduce the problem and working on a fix. 
Will keep you posted here.

**Comment by djozsef** [comment]
Hello @drochUNO @tomvweekes,

We have pushed the fix for the time range filter problem, it should work for you too now. Could you please check?

Thanks.

**Comment by safreeman** [comment]
Hi @djozsef 
Not sure the fix has worked? I have re-synced and still can't see any date/time dimensions?
Thanks
<img width="726" alt="screen shot 2018-01-31 at 11 39 22 am" src="https://user-images.githubusercontent.com/35980098/35599188-b16e2ff4-067b-11e8-8401-040ac3197d02.png">
<img width="1122" alt="screen shot 2018-01-31 at 11 39 39 am" src="https://user-images.githubusercontent.com/35980098/35599192-b407f5ec-067b-11e8-9283-2997e003e56d.png">
